[platformio]
default_envs = twatch-s3-headless
boards_dir = boards 

[env:twatch-s3-headless]
platform = espressif32
board = twatch-s3
framework = arduino
board_build.variants_dir = variants 

build_flags = 
    -D CORE_DEBUG_LEVEL=3

; --- Serial monitor ---
monitor_speed = 115200
monitor_filters = 
    esp32_exception_decoder
    time

; --- Dependencies ---
lib_deps =
    lewisxhe/XPowersLib @ ^0.2.1
    jgromes/RadioLib @ ^6.3.0