[platformio]

[env:t-watch-s3]
extends = esp32_base
board = t-watch-s3

board_build.variants_dir = variants

board_build.variant = esp32s3

build_src_filter = 
  ${esp32_base.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../variants/t_watch_s3/*.cpp>
  +<../src/helpers/sensors/*.cpp>

build_flags = 
  ${esp32_base.build_flags}
  -I variants/t_watch_s3
  -D TARGET_TWATCH_S3
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D MESHTASTIC_EXCLUDE_ROUTER=1
  -D MESHTASTIC_EXCLUDE_REPEATER=1
  -D ROLE_COMPANION_DEFAULT=1
  -D ENABLE_BLUETOOTH=1
  -D DISABLE_WIFI_ON_BOOT=1
  -D HAS_PMU=1

lib_ldf_mode = deep
lib_deps = 
  ${esp32_base.lib_deps}
  jgromes/RadioLib
  densaugeo/base64
  lewisxhe/XPowersLib@^0.2.1